spring:
  jpa:
    show-sql: true 
     
  datasource:
    url: jdbc:mysql://localhost:3306/book_catalog
    username: root
    password: Java@1230
    driver-class-name: com.mysql.cj.jdbc.Driver 